### PR TITLE
feat(analytics): provide option labels

### PR DESCRIPTION
**Pull request by winged**
Analytics now gives you the ability to not only extract slugs from choice
questions, but the corresponding labels as well.

### CODE REVIEW

**Review by fugal-dy — COMMENTED** [review]
this is all good, AFAICT =)

**Comment by open-dynaMIX** [comment]
Awesome @winged :tada:

Unfortunately the choice-questions are not correctly detected/handled and `is_leaf` is `true`. Here's part of the response as captured in the FE

```
                    {
                        "node": {
                            "id": "$SOME_ID",
                            "label": "chosenlabel",
                            "isLeaf": true,
                            "isValue": true,
                            "sourcePath": "document[foo].bar.baz",
                            "supportedFunctions": [
                                "VALUE",
                                "COUNT",
                                "MAX",
                                "MIN"
                            ],
                            "__typename": "AvailableField"
                        },
                        "__typename": "AvailableFieldEdge"
                    },
```

Just as a heads up: The same should also be implemented for `Form`. But this can also be done in a separate PR.

**Comment by open-dynaMIX** [comment]
Awesome @winged :tada:

We're making progress. I can now add the label-field and also fetch the correct results. However, explicitly setting the language doesn't work yet:

```json
{
    "errors": [
        {
            "message": "de",
            "locations": [
                {
                    "line": 10,
                    "column": 3
                }
            ],
            "path": [
                "analyticsTable",
                "availableFields"
            ]
        }
    ],
    "data": {
        "analyticsTable": {
            "id": "QW5hbHl0aWNzVGFibGU6ZmFjaGluZm9ybWF0aW9uZW4=",
            "availableFields": null,
            "__typename": "AnalyticsTable"
        }
    }
}
```

**Comment by open-dynaMIX** [comment]
@winged What's the status here?

**Review by open-dynaMIX — APPROVED** [review]
Awesome :tada:

**Pull request merged**
