### PR TITLE
Do not exclude documents in form schema

### PR DESCRIPTION
**Pull request by open-dynaMIX**
This change allows to have access to documents and even cases from
forms.

This is useful for triggering cases based on form properties (e.g.
meta).

### CODE REVIEW

**Comment by open-dynaMIX** [comment]
@winged I know what you mean, but honestly am a bit lost as to how to test this.

Any inputs would be very much appreciated.

**Comment by winged** [comment]
> @winged I know what you mean, but honestly am a bit lost as to how to test this.
> 
> Any inputs would be very much appreciated.

I don't think we explicitly need to test this. It's just a question on how graphene applies filters. To test this, you'd need an elaborate permissions setup I think

**Comment by open-dynaMIX** [comment]
@winged This seems to be handled in the VisibilityClasses, as can be seen [here](https://git.adfinis-sygroup.ch/fromarte/fromarte/blob/master/caluma/extensions/visibilities.py).

So I'd say, there are no security implications.

**Comment by czosel** [comment]
Yep, that's also what I was thinking :+1:

**Pull request merged**
