### PR TITLE
chore(test): use syrupy instead of snapshottest

### PR DESCRIPTION
**Pull request by sbor23**

### CODE REVIEW

**Comment by czosel** [comment]
What's the advantage of syrupy?

**Comment by sbor23** [comment]
> What's the advantage of syrupy?

It seems to handle dict ordering better!
It supports more pytest-idiomatic syntax so you can write `assert value == snapshot` instead of `snapshot.assert_match(value)`.
It doesn't write to a python file but has its own serialized data format, so `black` and `isort` won't care about it.

Also it's maintained compared to snapshottest which didn't have a release in a year.

**Comment by sbor23** [comment]
We might wanna move the `.ambr` snapshot files to commons license...

**Comment by winged** [comment]
Good to merge from my perspective, but I'd like @open-dynaMIX to have a quick glance as well :)

**Pull request merged**
