### PR TITLE
chore(deps): update graphene-django

### PR DESCRIPTION
**Pull request by sbor23**
Update to graphene-django 2.12.1 and fix connection field, schema.

fixes problem found in https://github.com/projectcaluma/caluma/pull/985

### CODE REVIEW

**Comment by winged** [comment]
LGTM, but note that this is a breaking change due to the schema changing types (`String` to `ID`; `[String]!` to `[String!]!`). Might wanna batch it and do it later when we have some other breaking changes as well (see #930 for example)

**Comment by sbor23** [comment]
> LGTM, but note that this is a breaking change due to the schema changing types (`String` to `ID`; `[String]!` to `[String!]!`). Might wanna batch it and do it later when we have some other breaking changes as well (see #930 for example)

True. However I made the id input variable a `graphene.String()` to stay as close as possible to the existing schema.

**Comment by winged** [comment]
> > LGTM, but note that this is a breaking change due to the schema changing types (`String` to `ID`; `[String]!` to `[String!]!`). Might wanna batch it and do it later when we have some other breaking changes as well (see #930 for example)
> 
> True. However I made the id input variable a `graphene.String()` to stay as close as possible to the existing schema.

It's still gonna break clients if they reference types

**Comment by sbor23** [comment]
Closing in favor of https://github.com/projectcaluma/caluma/pull/1413 which incorporates these fixes.

**Pull request closed without merging**
