### PR TITLE
chore(license): switch main license to GPL-3.0-or-later

### PR DESCRIPTION
**Pull request by ganwell**
Based on the discussion in issue #751, we reevaluated our goals. We want

-  diverse uses and integration of Caluma
-  Caluma to remain public as Free Software
-  an active community
-  to guarantee mutual benefit to our contributors

We found that the definitions in AGPL aren't as clearcut as we wished; therefore, we want to switch to GPL-3.0-or-later. GPL will support all of our goals, with a minor draw-back: Not every last modification is guaranteed to end up in public. Which isn't that bad and it resolves all discussion about configuration.

### CODE REVIEW

**Comment by anehx** [comment]
Looks good, there's only one unanswered question: what exact license are we using for the frontend packages?

**Comment by ganwell** [comment]
@anehx GPL-3.0-or-later is the only correct one. Its the official SPDX identifier.

**Comment by ganwell** [comment]
> The notation is a bit confusing, we should decide which one of those we use:
> 
> * GPL-3.0-or-later
> * GPLv3+
> * GPL-3.0

@anehx GPL-3.0-or-later is the only correct one. Its the official SPDX identifier. I can't change that pypi doesn't use the correct one and that the license text itself isn't consistent. I changed the badge, though. Let me know if I missed an occurrence.

**Comment by ganwell** [comment]
And GitHub does everything wrong, when it comes to licenses:

1. They use the wrong identifiers
2. They don't accept the SPDX license texts
3. They don't scan the right files

Many people opened issues, for some reason, they don't want to fix the problem.

**Pull request merged**
