### PR TITLE
fix(form): set questions of searchAnswers as required

### PR DESCRIPTION
**Pull request by Yelinz**
fixes bug from #656

not sure if breaking?

### CODE REVIEW

**Review by anehx — CHANGES_REQUESTED** [review]
Yes, this is breaking - please mark it as such. However I don't think the test is necessary since the schema test kind of already does that.

Otherwise LGTM.

**Comment by Yelinz** [comment]
> Yes, this is breaking - please mark it as such. However I don't think the test is necessary since the schema test kind of already does that.
> 
> Otherwise LGTM.

Added breaking to commit msg

**Comment by anehx** [comment]
@Yelinz as per the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/) the body must lead with `BREAKING CHANGE:`

**Comment by Yelinz** [comment]
> @Yelinz as per the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/) the body must lead with `BREAKING CHANGE:`

Done

**Comment by Yelinz** [comment]
Might be worth considering leaving it optional and implementing a search over all cases, will be discussed by @winged and @open-dynaMIX

**Review by winged — APPROVED** [review]
Nice catch, LGTM!

**Comment by winged** [comment]
> Might be worth considering leaving it optional and implementing a search over all cases, will be discussed by @winged and @open-dynaMIX

Had an offline discussion with @open-dynaMIX - best solution would be to keep it "required", but add additional syntax to explicitly state that a search across all answers is desired. We would perfer it to be explicit than implicit by just not specifying questions.

**Comment by anehx** [comment]
> Had an offline discussion with @open-dynaMIX - best solution would be to keep it "required", but add additional syntax to explicitly state that a search across all answers is desired. We would perfer it to be explicit than implicit by just not specifying questions.

I'd prefer that option as well, since a search across all answers might be very costly in terms of performance. This should only happen if explicitly required.

**Review by anehx — APPROVED** [review]

**Pull request merged**
