### PR TITLE
fix(validation): fix custom validation for save answer mutations

### PR DESCRIPTION
**Pull request by anehx**
Fixes a regression introduced in 6b71559eb7a1dca280de625c89d7b4e65c02decc

### CODE REVIEW

**Comment by sbor23** [comment]
Which exact case does this fix? Can you please create a test case for it?

We're a bit in a weird spot, because we try to streamline the the graphql and python APIs as much as possible. Now some validation still seems to happen in rest_framework only, which isn't covered in the domain_logic (and thus in the python API).
I would prefer if that case is handled in domain logic instead of calling into rest_framework, so that both APIs correct.

**Comment by anehx** [comment]
This fixes the custom validation classes which can't be used with the python API and yes I can write a test for this. However, I'd like to mention that this is the second fix I'm doing for this exact commit. The quality control has got to improve...

**Comment by anehx** [comment]
Added the test @sbor23

**Review by sbor23 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
