### PR TITLE
chore: update pyjexl

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Review by open-dynaMIX — CHANGES_REQUESTED** [review]
Change looks good.

It'd be senseful to have a commit message explaining why we're doing this. Otherwise LGTM.

**Comment by czosel** [comment]
True - done!

**Review by open-dynaMIX — APPROVED** [review]

**Comment by czosel** [comment]
cc @winged

**Comment by winged** [comment]
Hmm.. A comment in the requirements file would have been the "standard procedure" for this, so we know from looking at the code when to remove the explicit reference (and are reminded more often to go check for a release). No need to reopen however

**Pull request merged**
