### PR TITLE
fix(form): set allow_blank for static_content

### LINKED ISSUE #1576: static_content in staticQuestion is optional
The backend doesn't accept an empty string as `Static content`. On removal of this content, it needs to be set to `null`.

Steps to reproduce:

1. Save a question with `Static content`
2. Remove the `Static content`
3. Saving will now fail because the frontend sets `Static content` to `""`

### PR DESCRIPTION
**Pull request by Yelinz**
fixes #1576

### CODE REVIEW

**Comment by Yelinz** [comment]
If you want to use staticQuestion for an override component which doesnt display the text, for example a custom submit button in the form would be a staticQuestion without static_content

**Comment by czosel** [comment]
Ah I see, so it's a bit of an edge case. Fine by me :+1:

**Comment by Yelinz** [comment]
After some discussion it seems to be a problem of the `staticQuestion` schema, as `static_content` optional in the schema and therefore the frontend also marks it as an optional field. 
image
`static_content` should be required, otherwise the question would just be blank when its rendered which wouldn't make sense.

For the case of using a `staticQuestion` for an override component, a new question type of `widgetQuestion` should be created for that, instead of abusing a `staticQuestion`.

**Comment by czosel** [comment]
Much cleaner! 👍

**Pull request closed without merging**
