### PR TITLE
fix(API): use GenericScalar for meta fields

### PR DESCRIPTION
**Pull request by czosel**
BREAKING CHANGE: If you've been manually parsing the JSONString of a
meta field, you can remove that code - meta is automatically expanded now.

### CODE REVIEW

**Comment by winged** [comment]
What's the rationale behind this change? Why is it necessary?

**Comment by czosel** [comment]
We're expanding `meta` on several entities already (`GenericScalar` instead of `JSONString`). I think we should do that everywhere, since it makes it easier for the frontend and comes with no disadvantage.

**Comment by winged** [comment]
> We're expanding `meta` on several entities already (`GenericScalar` instead of `JSONString`). I think we should do that everywhere, since it makes it easier for the frontend and comes with no disadvantage.

In that case, why not change it on all entities?

**Comment by czosel** [comment]
I was afraid you'd say that :smile:

**Comment by czosel** [comment]
@winged done. Do you have an opinion about whether meta should be required?

**Comment by winged** [comment]
> @winged done. Do you have an opinion about whether meta should be required?

Meta should definitely not be required. It's only used for certain purposes, so if you're not using it, you shouldn't need to set it to some value

**Comment by winged** [comment]
Hmm I've just seen that `Question.meta` is required, while all others are not. Any reason for that?

**Comment by czosel** [comment]
No idea! Some of the `meta` field in the workflow schema are defined as `meta = JSONField(default=dict)` - that might also be reasonable?

/cc @open-dynaMIX

**Comment by winged** [comment]
I don't think the default has any use, really. It's a suggestion to use it as a dict, but it's not really required to do so (except that then filters like the one from #393 won't work in that situation). I'd rather leave it NULL instead if not used (saves a wee bit of storage as well)

**Comment by czosel** [comment]
Ok. Shall we move on with this then?

**Comment by czosel** [comment]
@winged Wanna approve it then? :wink:

**Pull request merged**
