### PR TITLE
feat(document): add source field referencing parent

### PR DESCRIPTION
**Pull request by sbor23**

### CODE REVIEW

**Comment by czosel** [comment]
Hmm, feels a bit strange when copying is not even possible within caluma, doesn't it?
cc @open-dynaMIX @anehx

**Comment by sbor23** [comment]
Migration will clash with https://github.com/projectcaluma/caluma/pull/913

**Comment by open-dynaMIX** [comment]
I agree with @czosel . I think we have two options:

1. Implement copying of documents in caluma and add this field
2. When copying is done outside of caluma, the `meta` field should be used for storing this kind of information.

> Migration will clash with #913

Did you mean to link to something else?

**Comment by sbor23** [comment]
Closing in favour of original PR https://github.com/projectcaluma/caluma/pull/898

**Pull request closed without merging**
