### PR TITLE
chore: fix gitlint config for dependabot

### PR DESCRIPTION
**Pull request by sbor23**

### CODE REVIEW

**Review by open-dynaMIX — APPROVED** [review]
Nice!

Personally I'd prefer just adding `title-max-length` to the [ignore line](https://github.com/projectcaluma/caluma/blob/master/.gitlint#L2) and allow more than 80 chars.

**Comment by sbor23** [comment]
> Nice!
> 
> Personally I'd prefer just adding `title-max-length` to the [ignore line](https://github.com/projectcaluma/caluma/blob/master/.gitlint#L2) and allow more than 80 chars.

This wouldn't suffice for current PRs already:
```

1s
Run gitlint --contrib contrib-title-conventional-commits
3: B1 Line exceeds max length (103>80): "Bumps [django-localized-fields](https://github.com/SectorLabs/django-localized-fields) from 6.2 to 6.4."
4: B1 Line exceeds max length (81>80): "- [Release notes](https://github.com/SectorLabs/django-localized-fields/releases)"
5: B1 Line exceeds max length (86>80): "- [Commits](https://github.com/SectorLabs/django-localized-fields/compare/v6.2...v6.4)"
Error: Process completed with exit code 3.
```

**Comment by open-dynaMIX** [comment]
In other projects we also use:

```
ignore=body-is-missing, body-max-line-length, body-min-length
```

**Comment by sbor23** [comment]
Aah I see, thanks for the pointer.

**Pull request merged**
