### PR TITLE
feat: dump_caluma command for entire forms

### PR DESCRIPTION
**Pull request by sbor23**
Dump an entire form as django fixtures using `./manage.py dump_caluma --model caluma_form.Form my-form-slug`.
This command lives in core so it can extended to other design-time aspects such as workflows, questions etc.

`load_caluma` is not necessary as the built-in `loaddata` does this already.

Partially addresses #1359

### CODE REVIEW

**Comment by winged** [comment]
(Not a review yet): Please add some documentation as to why it is neccessary and what it is for. Also not quite happy with the name... How about "export_config"?

**Comment by sbor23** [comment]
> (Not a review yet): Please add some documentation as to why it is neccessary and what it is for. 

Sure!

> Also not quite happy with the name... How about "export_config"?

IMO it should have "caluma" in it's name for usage as package / django apps in other projects.
Also `dump` aligns with what django uses for `dumpdata`, also implies that it produces django fixtures which are readable by `loaddata`.
Maybe `dump_caluma_config`?

**Comment by winged** [comment]
> IMO it should have "caluma" in it's name for usage as package / django apps in other projects.

Fair point, I didn't consider that perspective

> Maybe `dump_caluma_config`?

:+1:

**Review by winged — APPROVED** [review]
Nice work! :tada:

**Pull request merged**
