### PR TITLE
chore(release): release v5.8.1

### PR DESCRIPTION
**Pull request by sbor23**
### Performance
* Follow-up historicalanswer migration using SQL (2fad5bc5503497eacc4a1f264756d0f05680afe4)
* Add history_question_type to HistoricalAnswer (cb93e3853f9a7d50fe9720f98b86193d427fef34)

### CODE REVIEW

**Comment by open-dynaMIX** [comment]
Since  cb93e38 exposes the `question_history_type`, wouldn't it make more sense for this release to be `5.9.0`?

**Comment by sbor23** [comment]
> Since [cb93e38](https://github.com/projectcaluma/caluma/commit/cb93e3853f9a7d50fe9720f98b86193d427fef34) exposes the `question_history_type`, wouldn't it make more sense for this release to be `5.9.0`?

I would consider this change non-functional from an API point of view. The historical models is not something we normally consider, the sole use of this is performance.

**Comment by open-dynaMIX** [comment]
> > Since [cb93e38](https://github.com/projectcaluma/caluma/commit/cb93e3853f9a7d50fe9720f98b86193d427fef34) exposes the `question_history_type`, wouldn't it make more sense for this release to be `5.9.0`?
> 
> I would consider this change non-functional from an API point of view. The historical models is not something we normally consider, the sole use of this is performance.

I agree, that this addition to the schema is very small, so it's fine with me. But since we're exposing the historical API, we should generally view it as part of the public API.

**Comment by sbor23** [comment]
> I agree, that this addition to the schema is very small, so it's fine with me. But since we're exposing the historical API, we should generally view it as part of the public API.

Yes I was considering flagging the changes as a "fix", so it's a bit ambiguous.

**Pull request merged**
