### PR TITLE
GraphQL 3.0 tracking pull-request

### PR DESCRIPTION
**Pull request by ganwell**
Draft PR to track GraphQL 3.0 progress

This:

* https://github.com/graphql-python/graphene/issues/1312
* https://github.com/graphql-python/graphene-django/issues/1049

means that we finally have to take the GraphQL 3.0 problem seriously. I think we should maintain both projects.

@sbor23 @czosel @winged @open-dynaMIX @kaldras 

### Status

The tests are green because of [pytest-xfaillist](https://github.com/projectcaluma/pytest-xfaillist). xfail allows to expect tests to fail, but a test that is expected to fail and does not fail is a failure. This allows to track the progress much better.

- [ ] Fix snapshot tests
  - [ ] Find out what snapshot tests can be updated because of a valid change
  - [ ] Fix the rest e.g. the bugs
- [ ] ..... ?

### CODE REVIEW

**Comment by sbor23** [comment]
Thanks @ganwell for picking this up!

Just a heads up, I prepared https://github.com/projectcaluma/caluma/pull/1140 some time ago but we didn't merge it yet for deprecation reasons. I just rebased it, so there's a slim chance this works out of the box.

You could pick up the small fixes or rebase on top if it helps you in any way. :)

**Comment by ganwell** [comment]
> You could pick up the small fixes or rebase on top if it helps you in any way. :)

Nice, thanks to xfaillist, I could actually see if rebasing this flips any tests.

**Comment by sbor23** [comment]
There are some [upgrade notes for v3](https://github.com/graphql-python/graphene/wiki/v3-release-notes) which could prove handy.

**Comment by ganwell** [comment]
@sbor23 #1140 fixed 138 tests.

```python
In [9]: import json

In [10]: with open("xfails.list") as old:
    ...:     old_j = set(json.load(old))
    ...:

In [11]: with open("xfails.list.new") as new:
    ...:     new_j = set(json.load(new))
    ...:

In [12]: len(old_j - new_j)
Out[12]: 138

In [13]: len(new_j - old_j)
Out[13]: 0
```

**Comment by sbor23** [comment]
Alright, 57 fewer to go.

From what I've seen, there are 2 main issues:
* Enums: We quite a lot of enum fields for stuff like `status`, there are some changes, see https://github.com/graphql-python/graphene/issues/1277 and the [upgrade guide](https://github.com/graphql-python/graphene/wiki/v3-release-notes#backwards-incompatible-changes-in-30).
* Issues around the `Mutation` base class, we should resolve for this https://github.com/projectcaluma/caluma/issues/1081

**Comment by ganwell** [comment]
Superseeded by #1438

**Pull request closed without merging**
